blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/VIVA-Project/viva/discussions
    about: For general questions and discussions, please use Discussions
  - name: Documentation
    url: https://github.com/VIVA-Project/viva#readme
    about: Please check the documentation before opening an issue
